name: Compila APK Flutter
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true

      - name: Esegui la Build dell App
        run: |
          flutter pub get
          # Forza l'aggiornamento del pacchetto difettoso delle icone
          flutter pub upgrade font_awesome_flutter
          flutter clean
          flutter pub get
          flutter build apk --debug
          
      - name: Carica APK nei download
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
